stages:
  - stage: Build
    jobs:
      - job: 

  - stage: DEV
    displayName: Deploy in DEV
    jobs:
      - job:

  - stage: QA
    displayName: Deploy in DEV
    jobs:
      - job:

  - stage: PRD
    displayName: Deploy in PRD
    jobs:
      - job: