
pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: Build
    jobs:
      - job: 

  - stage: DEV
    displayName: Deploy in DEV
    jobs:
      - job:
        steps: 
      - task: UseDonNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: '6.x'
          performMultiLevelLookup: true
          includePreviewVersions: true # Required for preview versions

  - stage: QA
    displayName: Deploy in QA
    jobs:
      - job:

  - stage: PRD
    displayName: Deploy in PRD
    jobs:
      - job: